CREATE TABLE public.flight (
	flightid varchar(256) NOT NULL,
	FlightDate DATE,
	TailNum varchar(256),
	FlightNum varchar(256),
	Origin varchar(256),
	Dest varchar(256),
	CRSDepTime varchar(256),
	CRSArrTime varchar(256),
	ArrTime varchar(256), 
	ArrDelay varchar(256), 
	Cancelled varchar(256),
	WeatherDelay varchar(256),
	Diverted varchar(256),
	CONSTRAINT flight_pkey PRIMARY KEY (flightid)
);

CREATE TABLE public.location (
	LocationCode varchar(32) NOT NULL,
	LocationName varchar(256),
	LocationStateCode varchar(256),
	LocationStateFips varchar(256),
	LocationStateName varchar(256),
	CONSTRAINT location_pkey PRIMARY KEY (LocationCode)
);

CREATE TABLE public.weather (
	"date" DATE NOT NULL, 
	location varchar(32) NOT NULL, 
	"time" varchar(256) NOT NULL,
	mintempC INT4, 
	maxtempF INT4, 
	sunHour numeric(18,0), 
	mintempF int4, 
	maxtempC int4,
	uvIndex int4, 
	tempC int4, 
	windspeedKmph int4, 
	weather_Desc varchar(256), 
	HeatIndexC int4, 
	visibility int4, 
	weatherCode int4, 
	humidity int4,
	CONSTRAINT weather_pkey PRIMARY KEY (date, location, time)
);


CREATE TABLE public.flight_weather (
	flight_weather_id varchar(256) NOT NULL,
	flightId varchar(256),
	FlightDate DATE,
	CRSDepTime int4,
	Origin varchar(256),
	Dest varchar(256),
	ArrDelay BOOL,
	Cancelled BOOL, 
	WeatherDelay BOOL, 
	Diverted BOOL, 
	"time" varchar(32) NOT NULL,
	maxtempC int4,
	mintempC int4,
	tempC int4,
	weather_Desc varchar(256),
	CONSTRAINT flight_weather_pkey PRIMARY KEY (flight_weather_id),
	FOREIGN KEY(flightId) REFERENCES public.flight(flightId),
	FOREIGN KEY(Origin) REFERENCES public.location(LocationCode),
	FOREIGN KEY(Dest) REFERENCES public.location(LocationCode)
);


CREATE TABLE public.staging_flights (
	"Year" varchar(256), 
	"Quarter" varchar(256), 
	"Month" varchar(256), 
	DayofMonth varchar(256), 
	DayOfWeek varchar(256), 
	FlightDate DATE,
	UniqueCarrier varchar(256), 
	AirlineID varchar(256), 
	Carrier varchar(256), 
	TailNum varchar(256), 
	FlightNum varchar(256),
	OriginAirportID varchar(256), 
	OriginAirportSeqID varchar(256), 
	OriginCityMarketID varchar(256), 
	Origin varchar(256),
	OriginCityName varchar(256), 
	OriginState varchar(256), 
	OriginStateFips varchar(256), 
	OriginStateName varchar(256),
	OriginWac varchar(256), 
	DestAirportID varchar(256), 
	DestAirportSeqID varchar(256), 
	DestCityMarketID varchar(256), 
	Dest varchar(256), 
	DestCityName varchar(256), 
	DestState varchar(256),
	DestStateFips varchar(256),
	DestStateName varchar(256),
	DestWac varchar(256),
	CRSDepTime varchar(256),
	DepTime varchar(256), 
	DepDelay FLOAT4, 
	DepDelayMinutes FLOAT4,
	DepDel15 FLOAT4,
	DepartureDelayGroups FLOAT4,
	DepTimeBlk varchar(256),
	TaxiOut varchar(256),
	WheelsOff varchar(256),
	WheelsOn varchar(256),
	TaxiIn varchar(256),
	CRSArrTime varchar(256), 
	ArrTime varchar(256), 
	ArrDelay FLOAT4,
	ArrDelayMinutes FLOAT4, 
	ArrDel15 FLOAT4,
	ArrivalDelayGroups FLOAT4,
	ArrTimeBlk varchar(256),
	Cancelled varchar(256), 
	CancellationCode varchar(256), 
	Diverted varchar(256),
	CRSElapsedTime varchar(256),
	ActualElapsedTime varchar(256), 
	AirTime varchar(256), 
	Flights varchar(256),
	Distance varchar(256), 
	DistanceGroup varchar(256),
	CarrierDelay varchar(256), 
	WeatherDelay varchar(256), 
	NASDelay varchar(256), 
	SecurityDelay varchar(256),
	LateAircraftDelay varchar(256),
	FirstDepTime varchar(256),
	TotalAddGTime varchar(256),
	LongestAddGTime varchar(256),
	DivAirportLandings varchar(256),
	DivReachedDest varchar(256),
	DivActualElapsedTime varchar(256),
	DivArrDelay varchar(256),
	DivDistance varchar(256),
	Div1Airport varchar(256),
	Div1AirportID varchar(256),
	Div1AirportSeqID varchar(256),
	Div1WheelsOn varchar(256),
	Div1TotalGTime varchar(256),
	Div1LongestGTime varchar(256),
	Div1WheelsOff varchar(256),
	Div1TailNum varchar(256),
	Div2Airport varchar(256),
	Div2AirportID varchar(256),
	Div2AirportSeqID varchar(256),
	Div2WheelsOn varchar(256),
	Div2TotalGTime varchar(256),
	Div2LongestGTime varchar(256),
	Div2WheelsOff varchar(256),
	Div2TailNum varchar(256),
	Div3Airport varchar(256),
	Div3AirportID varchar(256),
	Div3AirportSeqID varchar(256),
	Div3WheelsOn varchar(256),
	Div3TotalGTime varchar(256),
	Div3LongestGTime varchar(256),
	Div3WheelsOff varchar(256),
	Div3TailNum varchar(256),
	Div4Airport varchar(256),
	Div4AirportID varchar(256),
	Div4AirportSeqID varchar(256),
	Div4WheelsOn varchar(256),
	Div4TotalGTime varchar(256),
	Div4LongestGTime varchar(256),
	Div4WheelsOff varchar(256),
	Div4TailNum varchar(256),
	Div5Airport varchar(256),
	Div5AirportID varchar(256),
	Div5AirportSeqID varchar(256),
	Div5WheelsOn varchar(256),
	Div5TotalGTime varchar(256),
	Div5LongestGTime varchar(256),
	Div5WheelsOff varchar(256),
	Div5TailNum varchar(256)
);

CREATE TABLE public.staging_weather (
	location varchar(256),
	mintempC varchar(256), 
	maxtempF varchar(256), 
	sunHour varchar(256), 
	mintempF varchar(256), 
	maxtempC varchar(256),
	"date" DATE, 
	uvIndex varchar(256),
	time varchar(256),
	tempC varchar(256), 
	windspeedKmph varchar(256), 
	weather_Desc varchar(256), 
	HeatIndexC varchar(256), 
	visibility varchar(256), 
	weatherCode varchar(256), 
	humidity varchar(256)
);
